name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I call sms.send()...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install package with 'npm install @gosmsge/gosmsge-node'
        2. Create SMS instance with '...'
        3. Call method '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The SMS should be sent successfully...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I got an error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { SMS } from '@gosmsge/gosmsge-node';

        const sms = new SMS('api_key');
        await sms.send('995555123456', 'Test', 'GOSMS.GE');
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Message/Stack Trace
      description: If applicable, paste the full error message or stack trace
      render: shell
      placeholder: |
        Error: ...
        at ...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @gosmsge/gosmsge-node are you using?
      placeholder: "3.3.8"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: "20.11.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - Development
        - Production
        - Testing
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "macOS 14.2, Ubuntu 22.04, Windows 11"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens when...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of the package
          required: false
        - label: I have provided all relevant information above
          required: true
